### ISSUE TITLE
Error when opening setting page

### ISSUE THREAD

**Issue by andannn** [andannn/aniflow#293]
When the exception was thrown, this was the stack: 
#0      new Flavor.fromJson (package:aniflow/core/common/environment/flavor.dart:13:70)
#1      BuildEnvironment.flavor (package:aniflow/core/common/environment/build_environment.dart:5:14)
#2      BuildEnvironment.isFeatureLimited (package:aniflow/core/common/environment/build_environment.dart:7:46)

**Comment by andannn** [comment]
https://github.com/andannn/aniflow/pull/296
